spring.application.name=backend
#change This to your Database credentials
#if you wanna use environment variables check out this article:
#https://www.baeldung.com/spring-boot-properties-env-variables
spring.datasource.url=jdbc:postgresql://localhost:5432/labuche

spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate.SQL=DEBUG


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update